### PR TITLE
Feature/tao 4814 bundler task

### PR DESCRIPTION
**Pull request by krampstudio**
Here is the 1st version of the atomic bundler for TAO.

It's a Gunt task, but relies on _independent_ modules (in `/lib`, by design there's no dependency to grunt) in order to bundle and transform TAO source code. 

The long list of options allows to set some default values and patterns, in order to reduce the required configuration from the bundling implementation. Some of the options have also been added in order to support the heterogeneous bundles in TAO without modifying the source code.

**How to test**

Except from running the repository tests (`npm test`), you can test it on TAO sources

1. Clone this repository locally and install it `npm i`
2. Link the repository `npm link`
3. From a TAO instance, most of the extensions have a branch `breaking/TAO-4814_atomic-bundles` which contains the correct configuration. At least update `tao-core` to the branch and some other extensions.
4. Into `tao/views/build`, remove the line '@oat-sa/grunt-tao-bundle` from the dependencies of the `package.json` (the repository is not yet published...) and run `npm link  @oat-sa/grunt-tao-bundle` so it will use the version linked in step 2.
5. bundle any extension using the same command as previously (`npx grunt ${extensionName.toLowerCase()}bundle` or `npx grunt bundle:${extensionName.toLowerCase()}`

### CODE REVIEW

**Review by no-chris — APPROVED** [review]
impressive work, congrats!

**Comment by krampstudio** [comment]
@no-chris I've added a fix : 
We've discovered during the testing a bug in the source map. It's fixed using `lib/sourceMapHelper.js` and tested with the related spec file.

**Comment by jsconan** [comment]
Just an addition to the main description, for the step 4 of the testing instructions you may also replace the dependency requirements by `"@oat-sa/grunt-tao-bundle": "git+ssh://git@github.com:oat-sa/grunt-tao-bundle.git#feature/TAO-4814_bundler_task"`. This is helpful if for any reason `npm link` does not work on your environment (for me it is because of `nvm`/`avn`).

**Review by jsconan — APPROVED** [review]
Impressive! With the previous implementation it took to my computer nearly 10 minutes or more to run a `grunt bundleall` task. Now it takes only ~2 minutes for the same task 👍

**Review by no-chris — APPROVED** [review]

**Pull request merged**
